data_root: data

data_ingestion:
  root_dir: data/raw
  source_url: https://raw.githubusercontent.com/MusaddiqueHussainLabs/datasets/main/taxi-fare-full.csv
  local_data_file: data/raw/taxi-fare-full.csv

data_validation:
  root_dir: data/interim
  input_data_dir: data/raw/taxi-fare-full.csv
  status_file_dir: data/interim/status.txt

data_transformation:
  root_dir: data/processed
  input_file_path: data/raw/taxi-fare-full.csv

data_loader:
  root_dir: data/processed
  input_file_path: data/raw/taxi-fare-full.csv

data_preprocessing:
  root_dir: data/processed
  input_file_path: data/raw/taxi-fare-full.csv

model_trainer:
  root_dir: models
  train_data_path: data/processed/taxi-fare-train.csv
  test_data_path: data/processed/taxi-fare-test.csv
  model_name: taxi_fare_prediction_model_v1.joblib

model_evaluation:
  root_dir: reports/evaluation_metrics
  test_data_path: data/processed/taxi-fare-test.csv
  model_path: models/taxi_fare_prediction_model_v1.joblib
  metric_file_name: reports/evaluation_metrics/taxi_fare_prediction_metrics.json