models:
  LinearRegression:
    regressor__fit_intercept: [True, False]
    regressor__copy_X: [True, False]
    regressor__n_jobs: [1, 2, 4, 8]
    regressor__positive: [True, False]
  RandomForestRegressor:
    regressor__bootstrap: [True]
    regressor__max_depth: [80, 90, 100, null]  # 'null' represents None
    regressor__max_features: ["sqrt", "log2", null]  # 'null' represents None
    regressor__min_samples_leaf: [1, 3, 5]
    regressor__min_samples_split: [2, 3, 4]
    regressor__n_estimators: [10, 25, 50, 75, 100]