LinearRegression:
  fit_intercept: True
  copy_X: True
  n_jobs: None
  positive: False
RandomForestRegressor:
  bootstrap: True,
  ccp_alpha: 0.0,
  criterion: squared_error,
  max_depth: None,
  max_features: 1.0,
  max_leaf_nodes: None,
  max_samples: None,
  min_impurity_decrease: 0.0,
  min_samples_leaf: 1,
  min_samples_split: 2,
  min_weight_fraction_leaf: 0.0,
  n_estimators: 100,
  n_jobs: None,
  oob_score: False,
  random_state: None,
  verbose: 0,
  warm_start: False
Ridge:
  alpha: 1.0,
  copy_X: True,
  fit_intercept: True,
  max_iter: None,
  positive: False,
  random_state: None,
  solver: auto,
  tol: 0.0001
Lasso:
  alpha: 1.0,
  copy_X: True,
  fit_intercept: True,
  max_iter: 1000,
  positive: False,
  precompute: False,
  random_state: None,
  selection: cyclic,
  tol: 0.0001,
  warm_start: False
SGDRegressor:
  alpha: 0.0001,
  average: False,
  early_stopping: False,
  epsilon: 0.1,
  eta0: 0.01,
  fit_intercept: True,
  l1_ratio: 0.15,
  learning_rate: invscaling,
  loss: squared_error,
  max_iter: 1000,
  n_iter_no_change: 5,
  penalty: l2,
  power_t: 0.25,
  random_state: None,
  shuffle: True,
  tol: 0.001,
  validation_fraction: 0.1,
  verbose: 0,
  warm_start: False
ElasticNet:
  alpha: 1.0,
  copy_X: True,
  fit_intercept: True,
  l1_ratio: 0.5,
  max_iter: 1000,
  positive: False,
  precompute: False,
  random_state: None,
  selection: cyclic,
  tol: 0.0001,
  warm_start: False
GradientBoostingRegressor:
  alpha: 0.9,
  ccp_alpha: 0.0,
  criterion: friedman_mse,
  init: None,
  learning_rate: 0.1,
  loss: squared_error,
  max_depth: 3,
  max_features: None,
  max_leaf_nodes: None,
  min_impurity_decrease: 0.0,
  min_samples_leaf: 1,
  min_samples_split: 2,
  min_weight_fraction_leaf: 0.0,
  n_estimators: 100,
  n_iter_no_change: None,
  random_state: None,
  subsample: 1.0,
  tol: 0.0001,
  validation_fraction: 0.1,
  verbose: 0,
  warm_start: False